spring.profiles.active=dev

# Datasource Configuration (Defaults for Dev, overridden by profile)
spring.datasource.url=jdbc:h2:mem:pfe_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate Configuration
spring.hibernate.hbm2ddl.auto=create-drop
spring.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.hibernate.show_sql=false
spring.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
